"""mig

Revision ID: 7bdb19e31789
Revises: 82de896c7b95
Create Date: 2021-06-21 11:51:06.860101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdb19e31789'
down_revision = '82de896c7b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number')
    # ### end Alembic commands ###
